server:
  port: 8080
  servlet:
    context-path: /moontruyen/api

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/moontruyen"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:moontruyen}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "ex6YyC9slbzxkFKTm59P4FzV6XpkT0/vCnqHsOHMUa+sltd/OZ1xYYTY3CnCvAwm"
  valid-duration: 86400 # in second
  refreshable-duration: 864000 #in second